### Server Side Prod ###
### STAGE 1: Build ###
FROM node:alpine AS build
WORKDIR /usr/src/app/client
COPY client/package*.json ./
RUN npm install -g @angular/cli && npm install
COPY client/ .
RUN npm run build:ssr
CMD ["node", "dist/app/server/main.js"]
